#MODULES=(i915 nvidia nvidia_modeset nvidia_uvm nvidia_drm)
MODULES=()

BINARIES=()

FILES=()

HOOKS=(base systemd autodetect microcode modconf kms keyboard keymap sd-vconsole block filesystems fsck)

# COMPRESSION
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-T0)
