#MODULES=(i915 nvidia nvidia_modeset nvidia_uvm nvidia_drm)
MODULES=()
BINARIES=()
FILES=()
HOOKS=(base systemd autodetect microcode modconf plymouth kms keyboard sd-vconsole block filesystems fsck)
COMPRESSION="zstd"
MODULES_DECOMPRESS="yes"
