# OPTIONS

[options]
Architecture = auto
HoldPkg = pacman glibc
NoExtract = boot/*-ucode.img

DownloadUser = alpm
ParallelDownloads = 15

Color
ILoveCandy
CheckSpace
VerbosePkgLists

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# REPOSITORIES

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
